repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

