site_name: "Dynamic Pricing"
theme:
  name: "material"
  palette:
    primary: "black"
  font:
      text: IBM Plex Sans
      code: SF Mono
nav:
- Deterministic models: notebooks/online_network_revenue_management/sim.md
- Thompson sampling: notebooks/thompson_sampling/nb_thompson_vs_greedy.md
- Dynamic programming: notebooks/dynamic_programming/nb_dynamic_programming.md
- Demand functions: notebooks/demand/nb_reservation_price_demand.md
- Online Network Revenue Management: 
      Simulation: notebooks/online_network_revenue_management/simulation.md
      Analysis: notebooks/online_network_revenue_management/analysis.md

markdown_extensions:
- codehilite:
      guess_lang: true
- pymdownx.arithmatex:
      generic: true
repo_name: Source Code
repo_url: https://github.com/denismaciel/dynamic-pricing-simulations
extra_javascript:
- javascripts/config.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
