site_name: "Dynamic Pricing"
theme:
  name: "material"
  palette:
    primary: "black"
  font:
      text: IBM Plex Sans
      code: SF Mono
nav:
  - Simulations:
    - Thompson Sampling: notebooks/nb_thompson_vs_greedy.md
markdown_extensions:
  - codehilite:
      guess_lang: true
repo_name: Source Code
repo_url: https://github.com/denismaciel/dynamic-pricing-simulations
